name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Generate contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: RohitWaghole
          outputs: |
            github-snake.svg?palette=github-light
            github-snake-dark.svg?palette=github-dark
            github-snake.gif?color_snake=#a855f7&color_dots=#161b22,#2e1065,#5b21b6,#7c3aed,#c084fc&color_background=#0d1117

      - name: Commit generated files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add github-snake.svg
          git add github-snake-dark.svg
          git add github-snake.gif

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "generated contribution snake"
            git push
          fi
